/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Files.Sucursales;
import cjb.ci.Validaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Basilio
 */
public class CrudSucursales extends javax.swing.JFrame
{

    /**
     * Creates new form CrudAntenas
     */
    public CrudSucursales()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        guardarSucursal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        gerenteSucursal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        direccionSucursal = new javax.swing.JTextField();
        nombreSucursal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nombreM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        direccionM = new javax.swing.JTextField();
        gerenteM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboSucursal = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        comboElimina = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaElimina = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(47, 113, 178));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guardarSucursal.setBackground(new java.awt.Color(0, 102, 204));
        guardarSucursal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardarSucursal.setForeground(new java.awt.Color(255, 255, 255));
        guardarSucursal.setText("GUARDAR");
        guardarSucursal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guardarSucursalActionPerformed(evt);
            }
        });
        jPanel2.add(guardarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        jLabel9.setText("Agregue los datos de la sucursal");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel10.setText("Nombre");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel11.setText("Gerente");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        gerenteSucursal.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                gerenteSucursalKeyTyped(evt);
            }
        });
        jPanel2.add(gerenteSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 310, -1));

        jLabel12.setText("Dirección");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        direccionSucursal.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                direccionSucursalKeyTyped(evt);
            }
        });
        jPanel2.add(direccionSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 310, -1));

        nombreSucursal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombreSucursalActionPerformed(evt);
            }
        });
        nombreSucursal.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombreSucursalKeyTyped(evt);
            }
        });
        jPanel2.add(nombreSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 310, -1));

        jTabbedPane1.addTab("Agregar Sucursal", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nombre");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        nombreM.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombreMActionPerformed(evt);
            }
        });
        nombreM.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombreMKeyTyped(evt);
            }
        });
        jPanel3.add(nombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 310, -1));

        jLabel5.setText("Gerente");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel6.setText("Dirección");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        direccionM.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                direccionMKeyTyped(evt);
            }
        });
        jPanel3.add(direccionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 310, -1));

        gerenteM.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                gerenteMKeyTyped(evt);
            }
        });
        jPanel3.add(gerenteM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 310, -1));

        jLabel8.setText("Modifique los datos de los campos que desea actualizar");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        comboSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboSucursal.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboSucursalItemStateChanged(evt);
            }
        });
        jPanel3.add(comboSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 240, -1));

        jLabel1.setText("Seleccione una sucursal");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jTabbedPane1.addTab("Modificar Sucursal", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboElimina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboElimina.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboEliminaItemStateChanged(evt);
            }
        });
        jPanel4.add(comboElimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 129, 225, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 342, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Selecione la sucursal que desea eliminar");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 79, 351, -1));

        tablaElimina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Nombre", "Gerente", "Dirección", "Torres Dependientes"
            }
        ));
        jScrollPane1.setViewportView(tablaElimina);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 183, 550, 110));

        jTabbedPane1.addTab("Eliminar Sucursal", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreMActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombreMActionPerformed
    {//GEN-HEADEREND:event_nombreMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMActionPerformed

    private void nombreSucursalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombreSucursalActionPerformed
    {//GEN-HEADEREND:event_nombreSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSucursalActionPerformed

    private void guardarSucursalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guardarSucursalActionPerformed
    {//GEN-HEADEREND:event_guardarSucursalActionPerformed
        if (nombreSucursal.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó por llenar el campo Nombre", "Alerta", JOptionPane.WARNING_MESSAGE);
            nombreSucursal.requestFocus();
        } else if (gerenteSucursal.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó por llenar el campo Gerente", "Alerta", JOptionPane.WARNING_MESSAGE);
            gerenteSucursal.requestFocus();
        } else if (direccionSucursal.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó por llenar el campo Dirección", "Alerta", JOptionPane.WARNING_MESSAGE);
            direccionSucursal.requestFocus();
        } else
        {
            Sucursales s = new Sucursales();
            s.altaSucursal(nombreSucursal, gerenteSucursal, direccionSucursal);
            s.agregaCombo(comboElimina);
            s.agregaCombo(comboSucursal);
        }

        nombreSucursal.setText("");
        gerenteSucursal.setText("");
        direccionSucursal.setText("");
    }//GEN-LAST:event_guardarSucursalActionPerformed

    private void comboSucursalItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboSucursalItemStateChanged
    {//GEN-HEADEREND:event_comboSucursalItemStateChanged
        Sucursales s = new Sucursales();
        s.selecSucursal(comboSucursal, nombreM, gerenteM, direccionM);
    }//GEN-LAST:event_comboSucursalItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        Sucursales s = new Sucursales();
        s.agregaCombo(comboSucursal);
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        if (comboSucursal.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this, "Faltó seleccionar la sucursal", "Alerta", JOptionPane.WARNING_MESSAGE);
            comboSucursal.requestFocus();
        } else if (nombreM.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó ingresar el nombre de la sucursal", "Alerta", JOptionPane.WARNING_MESSAGE);
            nombreM.requestFocus();
        } else if (gerenteM.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó ingresar el nombre del gerente", "Alerta", JOptionPane.WARNING_MESSAGE);
            gerenteM.requestFocus();
        } else if (direccionM.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó ingresar la dirección de la sucursal", "Alerta", JOptionPane.WARNING_MESSAGE);
            direccionM.requestFocus();
        } else
        {
            // Crear instancia de la clase Sucursales y modificar la sucursal
            Sucursales s = new Sucursales();
            s.modificarSucursal(nombreM, gerenteM, direccionM);

            // Limpiar campos después de modificar
            nombreM.setText("");
            gerenteM.setText("");
            direccionM.setText("");

            // Reiniciar el JComboBox para reflejar los cambios
            comboSucursal.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        Sucursales s = new Sucursales();
        s.eliminarSucursal(comboElimina);
        s.agregaCombo(comboElimina);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTabbedPane1MouseClicked
    {//GEN-HEADEREND:event_jTabbedPane1MouseClicked
        Sucursales s = new Sucursales();
        s.agregaCombo(comboElimina);
        s.agregaCombo(comboSucursal);
        s.consultaGeneralSucursalesContador(tablaElimina);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void comboEliminaItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboEliminaItemStateChanged
    {//GEN-HEADEREND:event_comboEliminaItemStateChanged
        Sucursales s = new Sucursales();
        s.consultaSucursalEspecifica(tablaElimina, comboElimina);
    }//GEN-LAST:event_comboEliminaItemStateChanged

    private void nombreSucursalKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreSucursalKeyTyped
    {//GEN-HEADEREND:event_nombreSucursalKeyTyped
        Validaciones.validaAlfanumerico(evt, 23, nombreSucursal.getText());
    }//GEN-LAST:event_nombreSucursalKeyTyped

    private void gerenteSucursalKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_gerenteSucursalKeyTyped
    {//GEN-HEADEREND:event_gerenteSucursalKeyTyped
        Validaciones.validaAlfabeticos(evt, 23, gerenteSucursal.getText());
    }//GEN-LAST:event_gerenteSucursalKeyTyped

    private void direccionSucursalKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_direccionSucursalKeyTyped
    {//GEN-HEADEREND:event_direccionSucursalKeyTyped
        Validaciones.validaAlfanumerico(evt, 23, direccionSucursal.getText());
    }//GEN-LAST:event_direccionSucursalKeyTyped

    private void nombreMKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreMKeyTyped
    {//GEN-HEADEREND:event_nombreMKeyTyped
        Validaciones.validaAlfanumerico(evt, 23, nombreM.getText());
    }//GEN-LAST:event_nombreMKeyTyped

    private void gerenteMKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_gerenteMKeyTyped
    {//GEN-HEADEREND:event_gerenteMKeyTyped
        Validaciones.validaAlfabeticos(evt, 23, gerenteM.getText());
    }//GEN-LAST:event_gerenteMKeyTyped

    private void direccionMKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_direccionMKeyTyped
    {//GEN-HEADEREND:event_direccionMKeyTyped
        Validaciones.validaAlfabeticos(evt, 23, direccionM.getText());
    }//GEN-LAST:event_direccionMKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CrudSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CrudSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CrudSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CrudSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CrudSucursales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboElimina;
    private javax.swing.JComboBox<String> comboSucursal;
    private javax.swing.JTextField direccionM;
    private javax.swing.JTextField direccionSucursal;
    private javax.swing.JTextField gerenteM;
    private javax.swing.JTextField gerenteSucursal;
    private javax.swing.JButton guardarSucursal;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nombreM;
    private javax.swing.JTextField nombreSucursal;
    private javax.swing.JTable tablaElimina;
    // End of variables declaration//GEN-END:variables
}
