/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Files.Clientes;
import Files.Fecha;
import Files.Sucursales;
import Files.Torres;
import cjb.ci.Validaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Basilio
 */
public class CrudClientes extends javax.swing.JFrame
{

    /**
     * Creates new form CrudClientes
     */
    public CrudClientes()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        IPCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        domicilioCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboSucursalCliente = new javax.swing.JComboBox<>();
        comboTorreCliente = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClienteTorre = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSucursalCliente = new javax.swing.JTable();
        fechaInstalacion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        comboModifTorre = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaModifSucursal = new javax.swing.JTable();
        comboModifSucursal = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        modifIP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        modifNombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboClientes = new javax.swing.JComboBox<>();
        modifDomicilio = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTorreCliente = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        comboEliminaCliente = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaEliminaCliente = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(47, 113, 178));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Agregue los datos del cliente");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel10.setText("Nombre");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel11.setText("IP");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        IPCliente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                IPClienteKeyTyped(evt);
            }
        });
        jPanel2.add(IPCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, -1));

        jLabel12.setText("Sucursal a la que pertenece");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        nombreCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombreClienteActionPerformed(evt);
            }
        });
        nombreCliente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombreClienteKeyTyped(evt);
            }
        });
        jPanel2.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, -1));

        domicilioCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                domicilioClienteActionPerformed(evt);
            }
        });
        domicilioCliente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                domicilioClienteKeyTyped(evt);
            }
        });
        jPanel2.add(domicilioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 180, -1));

        jLabel13.setText("Torre a la que pertenece");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel14.setText("Fecha de instalación");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel15.setText("Domicilio");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        comboSucursalCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboSucursalCliente.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboSucursalClienteItemStateChanged(evt);
            }
        });
        jPanel2.add(comboSucursalCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 110, -1));

        comboTorreCliente.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboTorreClienteItemStateChanged(evt);
            }
        });
        jPanel2.add(comboTorreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 110, -1));

        tablaClienteTorre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "No. Control", "Etiqueta", "Zona", "Dirección"
            }
        ));
        jScrollPane2.setViewportView(tablaClienteTorre);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 590, 50));

        tablaSucursalCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Nombre", "Gerente", "Dirección"
            }
        ));
        jScrollPane1.setViewportView(tablaSucursalCliente);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 590, 50));

        fechaInstalacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fechaInstalacion.setText("dd/mm/yyyy");
        jPanel2.add(fechaInstalacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 150, 180, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        jTabbedPane1.addTab("Agregar Cliente", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        jLabel8.setText("Modifique los datos de los campos que desea actualizar");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel16.setText("Torre a la que pertenece");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        comboModifTorre.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboModifTorreItemStateChanged(evt);
            }
        });
        jPanel3.add(comboModifTorre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 110, -1));

        tablaModifSucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Nombre", "Gerente", "Dirección"
            }
        ));
        jScrollPane5.setViewportView(tablaModifSucursal);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 590, 50));

        comboModifSucursal.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboModifSucursalItemStateChanged(evt);
            }
        });
        jPanel3.add(comboModifSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 110, -1));

        jLabel17.setText("Sucursal a la que pertenece");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        modifIP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                modifIPKeyTyped(evt);
            }
        });
        jPanel3.add(modifIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, -1));

        jLabel18.setText("IP");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel19.setText("Nombre");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        modifNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                modifNombreActionPerformed(evt);
            }
        });
        modifNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                modifNombreKeyTyped(evt);
            }
        });
        jPanel3.add(modifNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, -1));

        jLabel20.setText("Domicilio");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel1.setText("ClLIENTE:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        comboClientes.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboClientesItemStateChanged(evt);
            }
        });
        jPanel3.add(comboClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 500, -1));
        jPanel3.add(modifDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 170, -1));

        tablaTorreCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String []
            {
                "No. Control", "Zona", "Dirección", "Etiqueta", "Sucursal"
            }
        ));
        jScrollPane3.setViewportView(tablaTorreCliente);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 590, 50));

        jTabbedPane1.addTab("Modificar Cliente", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboEliminaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboEliminaCliente.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboEliminaClienteItemStateChanged(evt);
            }
        });
        jPanel4.add(comboEliminaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 99, 225, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Selecione el cliente que desea eliminar");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 65, 225, -1));

        tablaEliminaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "ID", "Nombre", "IP", "Fecha de Instalación", "Domicilio", "Estatus", "Sucursal", "Torre"
            }
        ));
        jScrollPane4.setViewportView(tablaEliminaCliente);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 177, 668, 110));

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 326, -1, -1));

        jTabbedPane1.addTab("Eliminar Cliente", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombreClienteActionPerformed
    {//GEN-HEADEREND:event_nombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreClienteActionPerformed

    private void domicilioClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_domicilioClienteActionPerformed
    {//GEN-HEADEREND:event_domicilioClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domicilioClienteActionPerformed

    private void modifNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_modifNombreActionPerformed
    {//GEN-HEADEREND:event_modifNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifNombreActionPerformed

    private void nombreClienteKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreClienteKeyTyped
    {//GEN-HEADEREND:event_nombreClienteKeyTyped
        Validaciones.validaAlfabeticos(evt, 23, nombreCliente.getText());
    }//GEN-LAST:event_nombreClienteKeyTyped

    private void IPClienteKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_IPClienteKeyTyped
    {//GEN-HEADEREND:event_IPClienteKeyTyped
        Validaciones.validaFlotantes(evt, 23, IPCliente.getText());
    }//GEN-LAST:event_IPClienteKeyTyped

    private void domicilioClienteKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_domicilioClienteKeyTyped
    {//GEN-HEADEREND:event_domicilioClienteKeyTyped
        Validaciones.validaAlfanumerico(evt, 23, domicilioCliente.getText());
    }//GEN-LAST:event_domicilioClienteKeyTyped

    private void modifNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_modifNombreKeyTyped
    {//GEN-HEADEREND:event_modifNombreKeyTyped
        Validaciones.validaAlfabeticos(evt, 23, nombreCliente.getText());
    }//GEN-LAST:event_modifNombreKeyTyped

    private void modifIPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_modifIPKeyTyped
    {//GEN-HEADEREND:event_modifIPKeyTyped
        Validaciones.validaFlotantes(evt, 23, IPCliente.getText());
    }//GEN-LAST:event_modifIPKeyTyped

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTabbedPane1MouseClicked
    {//GEN-HEADEREND:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        Fecha f = new Fecha();
        f.mostrarFechaEnCampo(fechaInstalacion);
        Clientes c = new Clientes();
        c.agregaCombo(comboClientes);
        c.agregaCombo(comboEliminaCliente);
        c.agregaComboSucursal(comboSucursalCliente);
        c.agregaComboSucursal(comboModifSucursal);
        c.agregaComboTorre(comboTorreCliente);
        c.agregaComboTorre(comboModifTorre);
        c.consultaGeneralClientes(tablaEliminaCliente);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // Validar que los campos no estén vacíos antes de dar de alta el cliente
        if (nombreCliente.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó ingresar el nombre del cliente", "Alerta", JOptionPane.WARNING_MESSAGE);
            nombreCliente.requestFocus();
        } else if (IPCliente.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó ingresar la IP del cliente", "Alerta", JOptionPane.WARNING_MESSAGE);
            IPCliente.requestFocus();
        } else if (fechaInstalacion.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó ingresar la fecha de instalación", "Alerta", JOptionPane.WARNING_MESSAGE);
            fechaInstalacion.requestFocus();
        } else if (domicilioCliente.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó ingresar el domicilio del cliente", "Alerta", JOptionPane.WARNING_MESSAGE);
            domicilioCliente.requestFocus();
        } else if (comboSucursalCliente.getSelectedItem() == null)
        {
            JOptionPane.showMessageDialog(this, "Faltó seleccionar la sucursal", "Alerta", JOptionPane.WARNING_MESSAGE);
            comboSucursalCliente.requestFocus();
        } else if (comboTorreCliente.getSelectedItem() == null)
        {
            JOptionPane.showMessageDialog(this, "Faltó seleccionar la torre", "Alerta", JOptionPane.WARNING_MESSAGE);
            comboTorreCliente.requestFocus();
        } else
        {
            // Crear instancia de la clase Clientes y dar de alta al cliente
            Clientes c = new Clientes();
            c.altaCliente(nombreCliente, IPCliente, fechaInstalacion, domicilioCliente, comboSucursalCliente, comboTorreCliente);
            c.agregaCombo(comboClientes);
            c.agregaCombo(comboEliminaCliente);

            // Limpiar los campos después de dar de alta el cliente
            nombreCliente.setText("");
            IPCliente.setText("");
            domicilioCliente.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboClientesItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboClientesItemStateChanged
    {//GEN-HEADEREND:event_comboClientesItemStateChanged
        Clientes c = new Clientes();
        c.selectCliente(comboClientes, modifNombre, modifIP, modifDomicilio, comboModifSucursal, comboModifTorre);
    }//GEN-LAST:event_comboClientesItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // Validar que los campos no estén vacíos antes de modificar el cliente
        if (modifNombre.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó ingresar el nombre del cliente", "Alerta", JOptionPane.WARNING_MESSAGE);
            modifNombre.requestFocus();
        } else if (modifIP.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó ingresar la IP del cliente", "Alerta", JOptionPane.WARNING_MESSAGE);
            modifIP.requestFocus();
        } else if (modifDomicilio.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó ingresar el domicilio del cliente", "Alerta", JOptionPane.WARNING_MESSAGE);
            modifDomicilio.requestFocus();
        } else if (comboModifSucursal.getSelectedItem() == null)
        {
            JOptionPane.showMessageDialog(this, "Faltó seleccionar la sucursal", "Alerta", JOptionPane.WARNING_MESSAGE);
            comboModifSucursal.requestFocus();
        } else if (comboModifTorre.getSelectedItem() == null)
        {
            JOptionPane.showMessageDialog(this, "Faltó seleccionar la torre", "Alerta", JOptionPane.WARNING_MESSAGE);
            comboModifTorre.requestFocus();
        } else
        {
            // Crear instancia de la clase Clientes y modificar el cliente
            Clientes c = new Clientes();
            c.modificarCliente(modifNombre, modifIP, modifDomicilio, comboModifSucursal, comboModifTorre);
            c.agregaCombo(comboClientes);
            c.agregaCombo(comboEliminaCliente);

            // Limpiar los campos después de modificar el cliente
            modifDomicilio.setText("");
            modifIP.setText("");
            modifNombre.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboModifSucursalItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboModifSucursalItemStateChanged
    {//GEN-HEADEREND:event_comboModifSucursalItemStateChanged
        Sucursales s = new Sucursales();
        s.consultaSucursalEspecifica(tablaModifSucursal, comboModifSucursal);
    }//GEN-LAST:event_comboModifSucursalItemStateChanged

    private void comboSucursalClienteItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboSucursalClienteItemStateChanged
    {//GEN-HEADEREND:event_comboSucursalClienteItemStateChanged
        Sucursales s = new Sucursales();
        s.consultaSucursalEspecifica(tablaSucursalCliente, comboSucursalCliente);
    }//GEN-LAST:event_comboSucursalClienteItemStateChanged

    private void comboEliminaClienteItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboEliminaClienteItemStateChanged
    {//GEN-HEADEREND:event_comboEliminaClienteItemStateChanged
        Clientes c = new Clientes();
        c.consultaClienteEspecifico(tablaEliminaCliente, comboEliminaCliente);
    }//GEN-LAST:event_comboEliminaClienteItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        Clientes c = new Clientes();
        c.eliminarCliente(comboEliminaCliente);
        c.agregaCombo(comboEliminaCliente);
        c.agregaCombo(comboClientes);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboModifTorreItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboModifTorreItemStateChanged
    {//GEN-HEADEREND:event_comboModifTorreItemStateChanged
        Torres t = new Torres();
        t.consultaTorreEspecifica(tablaTorreCliente, comboModifTorre);
    }//GEN-LAST:event_comboModifTorreItemStateChanged

    private void comboTorreClienteItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboTorreClienteItemStateChanged
    {//GEN-HEADEREND:event_comboTorreClienteItemStateChanged
        Torres t = new Torres();
        t.consultaTorreEspecifica(tablaClienteTorre, comboTorreCliente);
    }//GEN-LAST:event_comboTorreClienteItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CrudClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CrudClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CrudClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CrudClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CrudClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IPCliente;
    private javax.swing.JComboBox<String> comboClientes;
    private javax.swing.JComboBox<String> comboEliminaCliente;
    private javax.swing.JComboBox<String> comboModifSucursal;
    private javax.swing.JComboBox<String> comboModifTorre;
    private javax.swing.JComboBox<String> comboSucursalCliente;
    private javax.swing.JComboBox<String> comboTorreCliente;
    private javax.swing.JTextField domicilioCliente;
    private javax.swing.JLabel fechaInstalacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField modifDomicilio;
    private javax.swing.JTextField modifIP;
    private javax.swing.JTextField modifNombre;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTable tablaClienteTorre;
    private javax.swing.JTable tablaEliminaCliente;
    private javax.swing.JTable tablaModifSucursal;
    private javax.swing.JTable tablaSucursalCliente;
    private javax.swing.JTable tablaTorreCliente;
    // End of variables declaration//GEN-END:variables
}
